# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [3]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
print(np.__config__)
print(np.__version__)

<module 'numpy.__config__' from '/data/hu_paquette/.local/lib/python3.5/site-packages/numpy/__config__.py'>
1.17.0


#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆)

In [6]:
print(a.nbytes)

80


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [7]:
np.add?

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [8]:
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [9]:
a = np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [10]:
a = a[::-1]
print(a)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [11]:
a = np.arange(0,9)
a = a.reshape((3,3))
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [12]:
a = np.array([1,2,0,0,4,0])
print(np.where(a==0))

(array([2, 3, 5]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [13]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [14]:
a = np.random.rand(3,3,3)
print(a)

[[[0.43416325 0.21878154 0.21151447]
  [0.82935997 0.62820433 0.37989593]
  [0.49428032 0.42272266 0.37249083]]

 [[0.97523084 0.72583141 0.18715601]
  [0.5547446  0.20819614 0.04372698]
  [0.61123853 0.58111314 0.6060668 ]]

 [[0.72807436 0.69069634 0.15477449]
  [0.26541781 0.84893336 0.69757726]
  [0.89563681 0.08024238 0.94482158]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [15]:
a = np.random.rand(10,10)
print(a.min())
print(a.max())

0.009453537314915605
0.9766029902786222


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [16]:
a = np.random.rand(30)
print(a.mean())

0.5527613349511716


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [17]:
a = np.ones((5,5))
a[1:4,1:4] = 0
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [18]:
b = np.pad(a, 1)
print(b)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [19]:
# prediction
print('nan, true, false, nan, false, false')
# test
print(0 * np.nan) # nan !
print(np.nan == np.nan) # false ?
print(np.inf > np.nan) # false !
print(np.nan - np.nan) # nan !
print(np.nan in set([np.nan])) # true ?
print(0.3 == 3 * 0.1) # false !
# score : 4/6

nan, true, false, nan, false, false
nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [20]:
a = np.zeros((5,5))
for i in range(4):
    a[i+1,i] = i+1
print(a)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [21]:
a = np.zeros((8,8))
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        a[i,j] = divmod(i+j,2)[1]
print(a)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [22]:
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [23]:
a1 = np.array([[0, 1], [1, 0]])
a2 = np.tile(a1, (1,4))
a3 = np.tile(a2, (4,1))
print(a3)

a4 = np.tile(a1, (4,4))
print(a4)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [24]:
a = np.random.rand(5,5)
a = a / np.linalg.norm(a)
print(a)
print(np.linalg.norm(a))

[[0.27951952 0.24926428 0.30683075 0.33249973 0.09586082]
 [0.36602582 0.25615474 0.2271949  0.26563994 0.19386753]
 [0.1286244  0.07665036 0.00098263 0.06535801 0.04285946]
 [0.12020058 0.08013102 0.09264436 0.16288707 0.36634843]
 [0.02755178 0.1674655  0.13956972 0.06141481 0.12533532]]
1.0000000000000002


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [25]:
dt = np.dtype('b, b, b, b')
a = np.ones((3,3), dtype = dt)
print(a)

[[(1, 1, 1, 1) (1, 1, 1, 1) (1, 1, 1, 1)]
 [(1, 1, 1, 1) (1, 1, 1, 1) (1, 1, 1, 1)]
 [(1, 1, 1, 1) (1, 1, 1, 1) (1, 1, 1, 1)]]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [26]:
a = np.random.rand(5,3)
b = np.random.rand(3,2)
print(np.dot(a,b))
print(np.dot(a,b).shape)

[[1.22278147 1.43258218]
 [1.30204943 1.41474869]
 [0.69170767 0.86484863]
 [0.99380024 1.20018284]
 [0.96054465 0.99227998]]
(5, 2)


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [27]:
a = np.random.rand(10)
print(a)
a[4:8] *= -1
print(a)

[6.54032165e-01 1.99827580e-01 6.97667357e-01 5.91861314e-01
 5.02681160e-01 1.35803102e-01 8.41950756e-01 1.56042845e-01
 5.64302383e-01 5.04718928e-05]
[ 6.54032165e-01  1.99827580e-01  6.97667357e-01  5.91861314e-01
 -5.02681160e-01 -1.35803102e-01 -8.41950756e-01 -1.56042845e-01
  5.64302383e-01  5.04718928e-05]


#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [28]:
# predictions
print(9,10)

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9 10
10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [29]:
# prediction: 
# legal: Z**Z 
# 2 << Z >> 2
# Z <- Z
# legal: 1j*Z
# legal: Z/1/1
# Z<Z>Z
Z = np.array([1,2,3], dtype=np.int)
print(Z**Z) # !

[ 1  4 27]


In [33]:
print(2 << Z >> 2) # ? bit shift!

[1 2 4]


In [38]:
print(Z <- Z) # ? comparaison with negative Z

[False False False]


In [39]:
print(1j*Z) # !

[0.+1.j 0.+2.j 0.+3.j]


In [40]:
print(Z/1/1) # !

[1. 2. 3.]


In [41]:
print(Z<Z>Z) # !
# 4/6

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
# nan, 0, nan

In [42]:
np.array(0) / np.array(0)

/data/hu_paquette/.local/lib/python3.5/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


nan

In [43]:
np.array(0) // np.array(0)

/data/hu_paquette/.local/lib/python3.5/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


0

In [47]:
np.array([np.nan]).astype(int).astype(float) # ?? ohhhh int conversion doesnt understand special float so it just become a crazy large negative

array([-9.22337204e+18])

In [50]:
print(np.iinfo(np.int64))
print(np.array([np.nan]).astype(int))

Machine parameters for int64
---------------------------------------------------------------
min = -9223372036854775808
max = 9223372036854775807
---------------------------------------------------------------

[-9223372036854775808]


#### 29. How to round away from zero a float array ? (★☆☆)

In [51]:
# what does "away from 0 mean?"
np.round()
np.ceil()
np.floor()

array([ 6.54032165e-01,  1.99827580e-01,  6.97667357e-01,  5.91861314e-01,
       -5.02681160e-01, -1.35803102e-01, -8.41950756e-01, -1.56042845e-01,
        5.64302383e-01,  5.04718928e-05])

#### 30. How to find common values between two arrays? (★☆☆)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [52]:
# False, np.sqrt doesnt accept negative and therefore doesnt return complex
np.sqrt(-1) == np.emath.sqrt(-1)

/data/hu_paquette/.local/lib/python3.5/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in sqrt
  


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)